	PUBLIC	HELP
HELP:	EQU	$
	LXI	H, HELP_STR
	JMP	WRITE_LINE

HELP_STR: \
	EQU	$
	DB	LF
	GET_HELP_ENTRY 0
	GET_HELP_ENTRY 1
	GET_HELP_ENTRY 2
	GET_HELP_ENTRY 3
	GET_HELP_ENTRY 4
	GET_HELP_ENTRY 5
	GET_HELP_ENTRY 6
	GET_HELP_ENTRY 7
	GET_HELP_ENTRY 8
	GET_HELP_ENTRY 9
	GET_HELP_ENTRY 10
	GET_HELP_ENTRY 11
	GET_HELP_ENTRY 12
	GET_HELP_ENTRY 13
	GET_HELP_ENTRY 14
	GET_HELP_ENTRY 15
	DB	0	;END OF STRING