;
;
;
;
;      "set" COMMAND
;
;   THIS ROUTINE GETS THE ASSOCIATED PARAMETER AND
;   DISPATCHES TO THE PROPER ROUTINE FOR setTING
;   MEMORY VALUES.
;
	PUBLIC CSET
CSET:	call	find_next_arg	;SCAN TO SECONDARY COMMAND
	jz	error_handler	;MUST HAVE AT LEAST SOMETHING!!
	push	D	;SAVE SCAN ADDRESS
	call	get_hex_arg	;CONVERT FOLLOWING VALUE
	xthl		;HL=SAVED SCAN addr AND STACK=VALUE
	lxi	D,SETTAB	;SECONDARY COMMAND TABLE
	call	find_cmd	;TRY TO LOCATE IT
	jmp	DISP0	;OFF TO IT OR ERROR if NOT in TBL
;
;
;  THIS ROUTINE SETS THE TAPE SPEED
;
TASPD:	equ	$	;GET CONVERTED VALUE
	ora	A	;IS IT ZERO?
	jz	SETSP	;YES--THAT IS A PROPER SPEED
	mvi	A,32	;NO--set SPEED PROPERLY THEN
SETSP:	sta	TSPD
	ret
;
;
	PUBLIC STSPD
STSPD:	equ	$	;VDM ESCAPE SEQUENCE COMES HERE
	mov	A,B	;GET CHAR FOR FOLLOWING DISPD
DISPD:	equ	$	;set DISPLAY SPEED
	sta	SPEED
	ret
;
;
SETIN:	equ	$	;set AN INPUT PSUEDO PORT
	sta	IPORT
	ret
;
;
SETOT:	equ	$	;set AN OUTPUT PSUEDO PORT
	sta	OPORT
	ret
;
;
SETCI:	equ	$	;DEFINE USER INPUT RTN addr
	shld	USER_INP_PTR
	ret
;
;
SETCO:	equ	$	;DEFINE USER OUTPUT RTN addr
	shld	USER_OUT_PTR
	ret
;
;
SETTY:	equ	$	;set TAPE HDR TYPE
	sta	HTYPE
	ret
;
;
SETXQ:	equ	$	;set TAPE-EXECUTE addDR FOR HDR
	shld	XEQAD
	ret
;
;
SETNU:	equ	$	;HERE TO set NUMBER OF NULLS
	sta	NUCNT	;THIS IS IT
	ret
;
;
SETCR:	equ	$	;set CRC TO BE NORMAL, OR IGNORE CRC ERRORS
	sta	IGNCR	;FF=IGNORE CRC ERRORS, ELSE=NORMAL
	ret

; SECONDARY COMMAND TABLE FOR SET COMMAND
SETTAB:	\
	db	'TA'	;set TAPE SPEED
	dw	TASPD
	db	'S='	;set DISPLAY SPEED
	dw	DISPD
	db	'I='	;set INPUT PORT
	dw	SETIN
	db	'O='	;set OUTPUT PORT
	dw	SETOT
	db	'CI'	;set CUSTOM DRIVER ADDRESS
	dw	SETCI
	db	'CO'	;set CUSTOM OUTPUT DRIVER ADDRESS
	dw	SETCO
	db	'XE'	;set HEADER XEQ ADDRESS
	dw	SETXQ
	db	'TY'	;set HEADER TYPE
	dw	SETTY
	db	'N='	;set NUMBER OF NULLS
	dw	SETNU
	db	'CR'	;set CRC (NORMAL OR IGNORE CRC ERRORS)
	dw	SETCR
	db	0	;END OF TABLE MARK

