;
;
;
;
;      "SET" COMMAND
;
;   THIS ROUTINE GETS THE ASSOCIATED PARAMETER AND
;   DISPATCHES TO THE PROPER ROUTINE FOR SETTING
;   MEMORY VALUES.
;
	PUBLIC CSET
CSET:	CALL	FIND_NEXT_ARG	;SCAN TO SECONDARY COMMAND
	JZ	ERROR_HANDLER	;MUST HAVE AT LEAST SOMETHING!!
	PUSH	D	;SAVE SCAN ADDRESS
	CALL	GET_HEX_ARG	;CONVERT FOLLOWING VALUE
	XTHL		;HL=SAVED SCAN ADDR AND STACK=VALUE
	LXI	D,SETAB	;SECONDARY COMMAND TABLE
	CALL	FDCOM	;TRY TO LOCATE IT
	JMP	DISP0	;OFF TO IT OR ERROR IF NOT IN TBL
;
;
;  THIS ROUTINE SETS THE TAPE SPEED
;
TASPD:	EQU	$	;GET CONVERTED VALUE
	ORA	A	;IS IT ZERO?
	JZ	SETSP	;YES--THAT IS A PROPER SPEED
	MVI	A,32	;NO--SET SPEED PROPERLY THEN
SETSP:	STA	TSPD
	RET
;
;
	PUBLIC STSPD
STSPD:	EQU	$	;VDM ESCAPE SEQUENCE COMES HERE
	MOV	A,B	;GET CHAR FOR FOLLOWING DISPD
DISPD:	EQU	$	;SET DISPLAY SPEED
	STA	SPEED
	RET
;
;
SETIN:	EQU	$	;SET AN INPUT PSUEDO PORT
	STA	IPORT
	RET
;
;
SETOT:	EQU	$	;SET AN OUTPUT PSUEDO PORT
	STA	OPORT
	RET
;
;
SETCI:	EQU	$	;DEFINE USER INPUT RTN ADDR
	SHLD	USER_INP_PTR
	RET
;
;
SETCO:	EQU	$	;DEFINE USER OUTPUT RTN ADDR
	SHLD	USER_OUT_PTR
	RET
;
;
SETTY:	EQU	$	;SET TAPE HDR TYPE
	STA	HTYPE
	RET
;
;
SETXQ:	EQU	$	;SET TAPE-EXECUTE ADDDR FOR HDR
	SHLD	XEQAD
	RET
;
;
SETNU:	EQU	$	;HERE TO SET NUMBER OF NULLS
	STA	NUCNT	;THIS IS IT
	RET
;
;
SETCR:	EQU	$	;SET CRC TO BE NORMAL, OR IGNORE CRC ERRORS
	STA	IGNCR	;FF=IGNORE CRC ERRORS, ELSE=NORMAL
	RET
