	include src/const.asm
	include src/macros.asm
	include src/preamble.asm
	include src/entry.asm
	include src/console.asm
	include src/vdm.asm
	include src/startup.asm
	include src/command.asm
	include src/cassette.asm
	include src/memory.asm
