CUSET:	EQU	$	;TRY TO SET/CLEAR CUSTOM ROUTINE ADDR
	CALL	NAME0	;GET A NAME (S/B 2 CHARS OR MORE)
	LXI	H,COMND	;PT HERE IN CASE ADDR NOT GIVEN
	CALL	GET_OPT_HEX_ARG	;GET OPTIONAL OPERAND IF ANY
	PUSH	H	;SAVE THAT VALUE (IF ANY)
	LXI	H,THEAD	;PT TO NAME
	CALL	FIND_CUSTOM_CMD	;SEE IF NAME IS KNOWN IN CUST TABLE
	JZ	CUSE2	;NO--PROCEED TO KNOW IT
	DCX	D	;DE PT TO 1ST CHAR OF NAME IN TBL
	MVI	M,0	;(HL CAME BACK PT'ING TO THEAD)  CLR THIS NAME
CUSE2:	EQU	$	;ENTER NEW ONE IN TBL
	MOV	A,M	;GET 1ST CHAR OF NAME
	STAX	D	;PUT NAME INTO TABLE
	INX	D
	INX	H
	MOV	A,M	;GET 2ND CHAR OF NAME
	STAX	D	;NAME IS NOW POSTED
	INX	D	;PT TO 1ST BYTE OF ADDR
	POP	H	;RESTORE SAVED RTN ADDR
	XCHG		;DE=RTN ADDR, HL=THIS CU ENTRY
	MOV	M,E	;LO BYTE
	INX	H
	MOV	M,D	;AND HI BYTE
	RET		;ALL DONE
