EXTENSION_ID  equ 40h

;
;
;            SPECIAL CHAR ASSIGNMENTS
;
;  THESE DEFINITIONS ARE DESIGNED TO ALLOW
;  COMPATABILITY WITH SOLOS(TM). THESE ARE THE
;  SAME KEYS WITH BIT 7 (X'80') STRIPPED OFF.
;
DOWN:	equ	1AH	;CTL Z
UP:	equ	17H	;CTL W
LEFT:	equ	01H	;CTL A
RIGHT:	equ	13H	;CTL S
CLEAR:	equ	0BH	;CTL K
HOME:	equ	0EH	;CTL N
MODE:	equ	00H	;CTL-@
BACKS:	equ	5FH	;BACKSPACE
LF:	equ	10
CR:	equ	13
BLANK:	equ	' '
SPACE:	equ	BLANK
ESC:	equ	1BH