CALL_UNTIL_NZ	MACRO	ADDR
$$loop		CALL ADDR
		JZ $$loop
		ENDM

INPUT_ROUTINE	MACRO DATAPORT, STATUSPORT, STATUSFLAG, INVERTSTATUS
		IN STATUSPORT
		IF INVERTSTATUS == TRUE
		   CMA
		ENDIF
		ANI STATUSFLAG
		RZ
		IN DATAPORT
		RET
		ENDM

OUT_ROUTINE	MACRO	DATAPORT, STATUSPORT, STATUSFLAG
$$loop		IN STATUSPORT
		ANI STATUSFLAG
		JZ $$loop
		MOV A,B
		OUT DATAPORT
		RET
		ENDM
