;       S Y S T E M   G L O B A L    A R E A
;
	ORG    START+0800H	;RAM STARTS JUST AFTER ROM
;
SYSRAM:	EQU	$	;START OF SYSTEM RAM
SYSTP:	EQU	SYSRAM+3FFH	;STACK WORKS FM TOP DOWN
;
;
;   PARAMETERS STORED IN RAM
;
UIPRT:	DS	2	;USER DEFINED INPUT RTN IF NON ZERO
UOPRT:	DS	2	;USER DEFINED OUTPUT RTN IF NON ZERO
DFLTS:	DS	2	;DEFAULT PSUEDO I/O PORTS
IPORT:	DS	1	;CRNT INPUT PSUEDO PORT
OPORT:	DS	1	;CRNT OUTPUT PSUEDO PORT
NCHAR:	DS	1	;CURRENT CHARACTER POSITION
LINE:	DS	1	;CURRENT LINE POSITION
BOT:	DS	1	;BEGINNING OF TEXT DISPLACEMENT
SPEED:	DS	1	;SPEED CONTROL BYTE
ESCFL:	DS	1	;ESCAPE FLAG CONTROL BYTE
TSPD:	DS	1	;CURRENT TAPE SPEED
INPTR:	DS	2	;PTR TO NEXT CHAR POSITION IN INLIN
NUCNT:	DS	1	;NUMBER OF NULLS AFTER CRLF
IGNCR:	DS	1	;IGN CRC ERR FLAG, FF=IGN CRC ERRS, ELSE=NORMAL
;
	DS	10	;ROOM FOR FUTURE EXPANSION
;
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
;    T H I S   I S   T H E   H E A D E R   L A Y O U T    *
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
;
THEAD:	DS	5	;NAME
	DS	1	;THIS BYTE MUST BE ZERO
HTYPE:	DS	1	;TYPE
BLOCK:	DS	2	;BLOCK SIZE
LOADR:	DS	2	;LOAD ADDRESS
XEQAD:	DS	2	;AUTO EXECUTE ADDRESS
HSPR:	DS	3	;SPARES
;
HLEN:	EQU	$-THEAD	;LENGTH OF HEADER
BLKOF:	EQU	BLOCK-THEAD	;OFFSET TO BLOCK SIZE
DHEAD:	DS	HLEN	;A DUMMY HDR FOR COMPARES WHILE RD'ING
;
;
CUTAB:	DS	6*4	;ROOM FOR UP TO 6 CUSTOM USER COMMANDS
;
;
FNUMF:	DS	1	;FOR CURRENT FILE OPERATIONS
FCBAS:	DS	7	;1ST FILE CONTROL BLOCK
FCBA2:	DS	7	;2ND FILE CONTROL BLOCK
FBUF1:	DS	2*256	;SYSTEM FILE BUFFER BASE
	DS	1	;"BELL" (X'07') FLAGS START OF INPUT BFR
INLIN:	DS	80	;ROOM FOR THE INPUT LINE
USARE:	EQU	$	;START OF USER AREA
;
;   REMEMBER THAT THE STACK WORKS ITS WAY DOWN-FROM
;   THE END OF THIS 1K RAM AREA.
;
; -*-
