;
;
;
;                START UP SYSTEM
;
;   CLEAR SCREEN AND THE FIRST 256 BYTES OF GLOBAL RAM
;  THEN ENTER THE COMMAND MODE.
;
STRTA:	XRA	A
	MOV	C,A
	; Clear memory starting at DFLTS pointer
	; which is after custom user input/output routines.
	LXI	H,DFLTS	
;
-:	MOV	M,A
	INX	H
	INR	C
	JNZ	-
;
; DETERMINE THE DEFAULT PORTS
;     THIS COULD BECOME "MVI A,XX" FOR YOUR SPECIFIC PORTS
	IN	SENSE	;GET SWITCHES
;
	MOV	B,A	;SAVE IT
	ANI	3	;MAKE IT A VALID PORT
	STA	DFLTS+1	;SET DEFAULT OUTPUT PORT
	ORA	A	;SEE IF THIS THE VDM
	JNZ	STRTB	;NO--DO NOT RESET VDM
	LXI	SP,TOP_OF_STACK	;SET UP THE STACK FOR CALL
	CALL	ERASE_SCREEN	;(REG A ASSUMED TO COME BACK ZERO)
STRTB:	EQU	$	;FINISH OFF THIS PORT THEN DO NEXT
	LXI	H,0	;USE FOR CLEARING USER ADDRESSES
	CPI	3	;IS IT A USER PORT
	JZ	STRTC	;YES-- DO NOT CLEAR IT
	SHLD	USER_OUT_PTR	;NO--CLEAR ADDR
STRTC:	EQU	$	;OUTPUT PORT ALL SET
	MOV	A,B	;FM SENSE SWITCHES
	RAR
	RAR		;NEXT 2 BITS ARE INPUT PORT
	ANI	3	;VALID PORT
	STA	DFLTS	;THIS IS DEFAULT INPUT PORT
	CPI	3	;IS THIS ONE A USER PORT
	JZ	STRTD	;YES--DO NOT CLEAR IT THEN
	SHLD	USER_INP_PTR	;NO--FORCE USER ADDRESS ZERO
STRTD:	EQU	$	;1ST TIME INITIALIZATION ALL DONE NOW
	LHLD	DFLTS	;PICK UP DEFAULT PORTS
	SHLD	IPORT	;FORCE PORTS TO DEFAULT
SRST:	EQU	$	;RESET SERIAL PORT

RESET_PORT MACRO i
		IFDEF PSEUDO_i_STATUS_RESET_MASK
			MVI	A, PSEUDO_i_STATUS_RESET_MASK
			OUT	PSEUDO_i_STATUS_PORT
		ENDIF
		IFDEF PSEUDO_i_STATUS_SETUP_MASK
			MVI	A, PSEUDO_i_STATUS_SETUP_MASK
			OUT	PSEUDO_i_STATUS_PORT
		ENDIF
	ENDM
	RESET_PORT 0
	RESET_PORT 1
	RESET_PORT 2
	RESET_PORT 3


COMN1:	EQU	$	;HERE TO TURN OFF TAPES, THEN COMMAND MODE
	XRA	A
	OUT	TAPPT	;BE SURE TAPES ARE OFF
