	org	BASE_ADDRESS
;
;
;   AUTO-STARTUP CODE
;
START:	mov	A,A	;SHOW THIS IS CUTER (SOLOS=00)
;      THIS BYTE ALLOWS AUTOMATIC POWER ON ENTRY
;      WHEN in ROM SUPPORTING THIS HARDWARE FEATURE.
INIT:	jmp	startup_a	;SYSTEM RESTART ENTRY POINT
;
;   THESE JUMP POINTS ARE PROVIDED TO ALLOW COMMON ENTRY
; LOCATIONS FOR ALL VERSIONS OF CUTER.  THEY ARE USED
; EXTENSIVELY BY CUTS SYSTEM PROGRAMS AND IT IS RECOMMENDED
; THAT USER ROUTINES ACCESS CUTER ROUTINES THROUGH THESE
; POINTS ONLY!
;
RETRN:	jmp	COMND	;RETURN TO CUTER COMMAND PROCESSOR
FOPEN:	jmp	cassette_open	;CASSETTE OPEN FILE ENTRY
FCLOS:	jmp	cassette_close	;CASSETTE CLOSE FILE ENTRY
RDBYT:	jmp	cassette_read_byte	;CASSETTE READ BYTE ENTRY
WRBYT:	jmp	cassette_write_byte	;CASSETTE WRITE BYTE ENTRY
RDBLK:	jmp	cassette_read_block	;CASSETTE READ BLOCK ENTRY
WRBLK:	jmp	cassette_write_block	;CASSETTE WRITE BLOCK ENTRY
;
;     SYSTEM I/O ENTRY POINTS
;
;  THESE FOUR ENTRY POINTS ARE USED TO EITHER INPUT
;  OR OUTPUT TO CUTER PSUEDO PORTS.
;  THESE PSUEDO PORTS ARE AS FOLLOWS:
;
;  PORT   INPUT              OUTPUT
;  ----   -----------------  ---------------------
;   0     KEYBOARD INPUT     BUILT-in VDM DRIVER
;         ACTUAL PORT 3      PORT C8, MEMORY FROM CC00
;   1     SERIAL PORT        SERIAL PORT
;         ACTUAL PORT 10h    ACTUAL PORT 10h
;
;
;  NOTE: SOUT AND SINP ARE "lda" INSTRUCTIONS.
;        THIS FACT IS USED TO ALLOW ACCESS TO THE
;        BYTES "OPORT" AND "IPORT" DYNAMICALLY.
;        THESE MUST REMAIN "lda" INSTRUCTIONS!!!!!
;
SOUT:	lda	OPORT	;OUTPUT VIA STANDARD OUTPUT PSUEDO PORT
AOUT:	jmp	out_pseudo	;OUTPUT VIA PSUEDO PORT SPECIFIED IN REG A
SINP:	lda	IPORT	;INPUT VIA STANDARD INPUT PSUEDO PORT
AINP:	jmp	in_pseudo  ;INPUT VIA PSUEDO PORT SPECIFIED IN REG A
REGCMD: jmp	register_command	
